### ISSUE TITLE
Add database backend

### ISSUE THREAD

**Issue by agjohnson** [agjohnson/django-textclassifier#1]
Support more than one source for storing validator data by storing this information in a model instead of a flat file.

**Comment by humitos** [comment]
The current implementation uses a `TextField` in the database, so I think this issue can be closed.

I was about to suggest to use `JSONField` instead but that will make it only compatible with Django > 1.11 and PostgreSQL.

**Comment by agjohnson** [comment]
Yeah, there is always the third party JSONField as well, but i don't know how to make them play nicely together. If we want to fix this, we can always migrate.
